#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Joyces.Droid.Resource", IsApplication=true)]

namespace Joyces.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::Joyces.Droid.Resource.String.library_name;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Joyces.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Joyces.Droid.Resource.String.Hello;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::Joyces.Droid.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::Joyces.Droid.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::Joyces.Droid.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int fontPath = 2130771974;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060008
			public const int common_google_signin_btn_text_dark = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int common_google_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int common_google_signin_btn_text_dark_disabled = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_signin_btn_text_dark_focused = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_signin_btn_text_dark_pressed = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int common_google_signin_btn_text_light = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int common_google_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_signin_btn_text_light_disabled = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_signin_btn_text_light_focused = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_google_signin_btn_text_light_pressed = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_signin_btn_tint = 2131099658;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backArrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_full_open_on_phone = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_disabled = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_normal_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_focused = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_normal = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal_background = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_disabled = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_focused = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_normal = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal_background = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int googleg_disabled_color_18 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int googleg_standard_color_18 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Icon = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int IconNotification = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int IconPar = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int logo = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Logo_inside_paradiset = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Logo_inside_paradiset_green = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int logo_joyces = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Placeholder = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int profile = 2130837534;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070027
			public const int EmailEditText = 2131165223;
			
			// aapt resource value: 0x7f07002b
			public const int ForgotButton = 2131165227;
			
			// aapt resource value: 0x7f070030
			public const int MoreView = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int MoreViewList = 2131165233;
			
			// aapt resource value: 0x7f070036
			public const int OfferSingleView = 2131165238;
			
			// aapt resource value: 0x7f070028
			public const int PasswordEditText = 2131165224;
			
			// aapt resource value: 0x7f07002a
			public const int RegisterButton = 2131165226;
			
			// aapt resource value: 0x7f070001
			public const int adjust_height = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int adjust_width = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int auto = 2131165191;
			
			// aapt resource value: 0x7f070020
			public const int btnForgotViewSubmit = 2131165216;
			
			// aapt resource value: 0x7f070046
			public const int btnProfileViewLogout = 2131165254;
			
			// aapt resource value: 0x7f070045
			public const int btnProfileViewUpdate = 2131165253;
			
			// aapt resource value: 0x7f070052
			public const int btnRegisterViewRegister = 2131165266;
			
			// aapt resource value: 0x7f070050
			public const int buttonRegisterViewPrivacyPolicy = 2131165264;
			
			// aapt resource value: 0x7f07004f
			public const int buttonRegisterViewTermAndCondition = 2131165263;
			
			// aapt resource value: 0x7f07002c
			public const int buttonwMainViewVersion = 2131165228;
			
			// aapt resource value: 0x7f070000
			public const int calligraphy_tag_id = 2131165184;
			
			// aapt resource value: 0x7f07004e
			public const int chbRegisterViewTerms = 2131165262;
			
			// aapt resource value: 0x7f070056
			public const int contentFrame = 2131165270;
			
			// aapt resource value: 0x7f070008
			public const int dark = 2131165192;
			
			// aapt resource value: 0x7f070017
			public const int editTextDeveloperMenuBundleId = 2131165207;
			
			// aapt resource value: 0x7f070015
			public const int editTextDeveloperMenuDeviceToken = 2131165205;
			
			// aapt resource value: 0x7f07001d
			public const int editTextDeveloperMenuStatusREST = 2131165213;
			
			// aapt resource value: 0x7f07001a
			public const int editTextDeveloperMenuStatusWSO2 = 2131165210;
			
			// aapt resource value: 0x7f07001c
			public const int editTextDeveloperMenuUrlRest = 2131165212;
			
			// aapt resource value: 0x7f070019
			public const int editTextDeveloperMenuUrlWSO2 = 2131165209;
			
			// aapt resource value: 0x7f070004
			public const int icon_only = 2131165188;
			
			// aapt resource value: 0x7f070022
			public const int idviewLinearBack = 2131165218;
			
			// aapt resource value: 0x7f07002d
			public const int imageViewMore = 2131165229;
			
			// aapt resource value: 0x7f07000a
			public const int imageViewNews = 2131165194;
			
			// aapt resource value: 0x7f070033
			public const int imageViewNews2 = 2131165235;
			
			// aapt resource value: 0x7f07003c
			public const int imageViewNewsQRCode = 2131165244;
			
			// aapt resource value: 0x7f070011
			public const int imageViewOffer = 2131165201;
			
			// aapt resource value: 0x7f070023
			public const int imageViewQRId = 2131165219;
			
			// aapt resource value: 0x7f070009
			public const int light = 2131165193;
			
			// aapt resource value: 0x7f070032
			public const int listViewNewsfeed = 2131165234;
			
			// aapt resource value: 0x7f070037
			public const int listViewOffers = 2131165239;
			
			// aapt resource value: 0x7f070029
			public const int loginButton = 2131165225;
			
			// aapt resource value: 0x7f07001e
			public const int mLlayoutBottomButtons = 2131165214;
			
			// aapt resource value: 0x7f070025
			public const int mainViewBackground = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int mainViewLogo = 2131165222;
			
			// aapt resource value: 0x7f070057
			public const int menu_profile = 2131165271;
			
			// aapt resource value: 0x7f070003
			public const int none = 2131165187;
			
			// aapt resource value: 0x7f070012
			public const int scrollViewDeveloperMenu = 2131165202;
			
			// aapt resource value: 0x7f070005
			public const int standard = 2131165189;
			
			// aapt resource value: 0x7f07000d
			public const int textView1 = 2131165197;
			
			// aapt resource value: 0x7f070021
			public const int textView2 = 2131165217;
			
			// aapt resource value: 0x7f070024
			public const int textView3 = 2131165220;
			
			// aapt resource value: 0x7f07000c
			public const int textViewDescription = 2131165196;
			
			// aapt resource value: 0x7f070035
			public const int textViewDescription2 = 2131165237;
			
			// aapt resource value: 0x7f070016
			public const int textViewDeveloperMenuBundleId = 2131165206;
			
			// aapt resource value: 0x7f070014
			public const int textViewDeveloperMenuDeviceToken = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int textViewDeveloperMenuHeadline = 2131165203;
			
			// aapt resource value: 0x7f07001b
			public const int textViewDeveloperMenuStatusREST = 2131165211;
			
			// aapt resource value: 0x7f070018
			public const int textViewDeveloperMenuStatusWSO2 = 2131165208;
			
			// aapt resource value: 0x7f07003b
			public const int textViewDutyText2 = 2131165243;
			
			// aapt resource value: 0x7f07000b
			public const int textViewHeadline = 2131165195;
			
			// aapt resource value: 0x7f070034
			public const int textViewHeadline2 = 2131165236;
			
			// aapt resource value: 0x7f07002f
			public const int textViewMoreDescription = 2131165231;
			
			// aapt resource value: 0x7f07002e
			public const int textViewMoreHeadline = 2131165230;
			
			// aapt resource value: 0x7f07000f
			public const int textViewNote = 2131165199;
			
			// aapt resource value: 0x7f070039
			public const int textViewOfferValue2 = 2131165241;
			
			// aapt resource value: 0x7f07003d
			public const int textViewProfileViewEmail = 2131165245;
			
			// aapt resource value: 0x7f070041
			public const int textViewProfileViewFirstname = 2131165249;
			
			// aapt resource value: 0x7f070043
			public const int textViewProfileViewLastname = 2131165251;
			
			// aapt resource value: 0x7f07003f
			public const int textViewProfileViewMobileNo = 2131165247;
			
			// aapt resource value: 0x7f070051
			public const int textViewRegisterViewGhost1 = 2131165265;
			
			// aapt resource value: 0x7f07003a
			public const int textViewValidDate2 = 2131165242;
			
			// aapt resource value: 0x7f070010
			public const int textViewValidDateTime = 2131165200;
			
			// aapt resource value: 0x7f07000e
			public const int textViewValue = 2131165198;
			
			// aapt resource value: 0x7f07001f
			public const int txtForgotViewEmail = 2131165215;
			
			// aapt resource value: 0x7f07003e
			public const int txtProfileViewEmail = 2131165246;
			
			// aapt resource value: 0x7f070042
			public const int txtProfileViewFirstName = 2131165250;
			
			// aapt resource value: 0x7f070044
			public const int txtProfileViewLastName = 2131165252;
			
			// aapt resource value: 0x7f070040
			public const int txtProfileViewMobileNo = 2131165248;
			
			// aapt resource value: 0x7f070047
			public const int txtRegisterViewEmail = 2131165255;
			
			// aapt resource value: 0x7f07004a
			public const int txtRegisterViewFirstName = 2131165258;
			
			// aapt resource value: 0x7f07004b
			public const int txtRegisterViewLastName = 2131165259;
			
			// aapt resource value: 0x7f070049
			public const int txtRegisterViewMobileNo = 2131165257;
			
			// aapt resource value: 0x7f070048
			public const int txtRegisterViewMobileNoCountry = 2131165256;
			
			// aapt resource value: 0x7f07004c
			public const int txtRegisterViewPassword1 = 2131165260;
			
			// aapt resource value: 0x7f07004d
			public const int txtRegisterViewPassword2 = 2131165261;
			
			// aapt resource value: 0x7f070053
			public const int txtRegisterViewPersonalNumber = 2131165267;
			
			// aapt resource value: 0x7f070055
			public const int txtTerms = 2131165269;
			
			// aapt resource value: 0x7f070054
			public const int txtTermsHeader = 2131165268;
			
			// aapt resource value: 0x7f070038
			public const int viewpager = 2131165240;
			
			// aapt resource value: 0x7f070006
			public const int wide = 2131165190;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomListViewRowNewsfeed = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomListViewRowOffers = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DeveloperMenuView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ForgotView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int IdView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainParadiset = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MoreCellView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MoreView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int NewsfeedView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int NewsView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int OfferSingleView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int OffersView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int OfferView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ProfileView = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int RegisterView = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int RegisterViewParadiset = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int zxingscanneractivitylayout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int zxingscannerfragmentlayout = 2130903058;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int ToolbarMenu = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040013
			public const int ApplicationName = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int Hello = 2130968594;
			
			// aapt resource value: 0x7f040015
			public const int app_name = 2130968597;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_enable_button = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_enable_text = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int common_google_play_services_enable_title = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_install_button = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_install_text = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_title = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_notification_ticker = 2130968584;
			
			// aapt resource value: 0x7f040001
			public const int common_google_play_services_unknown_issue = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_unsupported_text = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_update_button = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_update_text = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_update_title = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_updating_text = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_wear_update_text = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int common_open_on_phone = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int common_signin_button_text = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int common_signin_button_text_long = 2130968593;
			
			// aapt resource value: 0x7f040014
			public const int hello = 2130968596;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int CheckBoxCustomStyle = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int CustomActionBarTheme = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int MyActionBar = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int SplashScreen = 2131230726;
			
			// aapt resource value: 0x7f080004
			public const int custom_actionBarTabBarStyle = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int custom_actionBarTabStyle = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int custom_tabViewStyle = 2131230725;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
